"""add_pdf_analyzer

Revision ID: e6e0c335dd44
Revises: 20260606_0001
Create Date: 2026-06-06 10:00:31.418167+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e0c335dd44'
down_revision: Union[str, None] = '20260606_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('chat_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_analyses_user_id'), 'pdf_analyses', ['user_id'], unique=False)
    op.drop_index('ix_ai_drafts_created_at', table_name='ai_drafts')
    op.drop_index('ix_email_threads_created_at', table_name='email_threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_email_threads_created_at', 'email_threads', ['created_at'], unique=False)
    op.create_index('ix_ai_drafts_created_at', 'ai_drafts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_pdf_analyses_user_id'), table_name='pdf_analyses')
    op.drop_table('pdf_analyses')
    # ### end Alembic commands ###
